### ISSUE TITLE
Improve Attachment Behavior

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#151]
Many of the tasks associated with automation benefit from our new ability to tell which cards are attached to a card, the most obvious being the automation of harmonize. We should update other such interactions to take attachments into account.

**Comment by sIKE23** [comment]
I am not sure why Cosworth excluded the Mage from Harmonize. Should be simple:
else:
if c2 and 'Channeling' in c2.Stats and c2.Type==  "'Magestats": #Exclude mages
                                me.Channeling += 1
                                whisper("Mana added to {} from {}".format(c2,c))

Logic will need to be added to remove the Channeling boost if the card is detached from the mage also.

I know we haven't discussed this, but current form in OCTGN is to place Enchantments to the side of the board near the players Magestats card. How do you think we should handle this? In the example above I used the Magestats card but that was just a place holder in my mind. I have not put a lot of thought into this. However testing last night with Juli I attached the Forcefield card to the mage card itself. I could not see the number of Forcefield tokens. :( 

Just some food for thought.

**Comment by anandaguneratne** [comment]
Regarding placement of enchantments to the side of the board:

Currently, there is no good way to detect enchantments that are not attached to anything. It works with equipment because equipment is always attached to your mage (so you can just search the table for face-up equipment), but there are numerous reasons why an enchantment might be face-up.

Once we can define zones, we can solve this problem by simply defining a box that represents the player's area, and treating enchantments inside that box as attached to them. Until then, we will just have to ignore the enchantments that are not attached to anything. My hope is that with the convenience of the card attachment module, players will start attaching their enchantments to their mages (I assume that the convention before was brought about by the difficulty of moving mages along with their enchantments, and of figuring out which attachments were attached to which objects).

**Comment by anandaguneratne** [comment]
As for forcefield tokens, I suppose you could put them on the mage/magestats.

**Comment by sIKE23** [comment]
On Attachment spacing, Schwenkgott came up with what I think is the proper abount of overlap, just a little bit more space between each card so we can read the mana cost and target line.

**Comment by anandaguneratne** [comment]
Okay, I'll change that.

**Comment by sIKE23** [comment]
Is it possible to have a different offset for attached cards based of differing criteria. For example Wands (better is Spellbind objects) it is common to have the text part of the card (lower 1/3) out of the bottom. Unrevealed Enchantments Stack to the bottom of a card and revealed attachments to the top and the highlight gets turned off?

**Comment by anandaguneratne** [comment]
Different offsets: Yes, that is possible. In fact, I would prefer that bound/prepared spells be treated differently from attachments. It will take a little while, since I will most likely have to make a separate system for bound objects (or just work an exception into the existing system)

Unrevealed on bottom and revealed at top: This would be tricky (but possible), but I don't think it is advisable. Knowing the order of attachments is important, and it is much easier to see when they are all in the same stack, rather than two different stacks. Also, if bound/prepared spells are on the bottom, then this would be a problem when, for instance, Wizard's Tower has a spell bound and also has an unrevealed reinforce on it.

Turning off highlight: This might be possible; unfortunately, the highlight on unrevealed cards is something OCTGN does automatically. But I could certainly try to eliminate it.

**Comment by sIKE23** [comment]
Knowing the order of *hidden* attachments is important. As for the offset
couldn't you just make it variable:

add a couple lines before the line below offset = 12

change Y = y-(count*side)*12 to Y = y-(count*side)*offset

then add a check for the Spellbind trait and if it is positive change the
offset


With further thought the Unrevealed on bottom and revealed at top idea is a
bad one.

Highlighting is handled by card.highlight() the problem is with how we are
arranging the cards the highlight is covering the part of the card we
wanted to see by increasing the reveal...you might need to dl and zoom
in to see what I am talking about.

[image: Inline image 1]

Thanks!

</sIKE>

**Comment by anandaguneratne** [comment]
If that is meant to be a link, it is not working for me.

**Comment by sIKE23** [comment]
you can find it at MageWars-Dev\AttachStack.jpg

**Comment by sIKE23** [comment]
An unbound Fire Ball when cast says: <player> casts 'Fireball' which is Spellbound, it has a printed casting cost of 8

**Comment by ACG8** [comment]
I don't understand what you mean.

**Comment by sIKE23** [comment]
I guess the question is how do you "Target" with an Unbound Attack Spell? From Source Mage to Target or Attack Spell to Target?

**Comment by ACG8** [comment]
From Source Mage to target. Try it; it should work.

**Comment by sIKE23** [comment]
We are changing twice for spells

sIKE says

> sike23 turns 'Arc Lightning' face up, it has a printed casting cost of 5
> sike23 pays 5 mana from pool for 'Arc Lightning'
> sike23 targets 'Warlock' with 'Wizard (Air)'
> sike23 casts 'Arc Lightning' which is Spellbound, it has a printed casting cost of 5
> sike23 pays 5 mana from pool for 'Arc Lightning'
> sike23 targets 'Warlock' with 'Wizard (Air)'
> Wizard (Air) attacks Warlock with Arc Lightning!
> sike23 rolls 3 attack dice 
> sike23 rolled 1 normal damage, 0 critical damage, and 4 on the effect die

**Comment by ACG8** [comment]
I already fixed this a few days ago, though. Attack spells should not ever be charging the player when revealed, unless that player has the BC turned off. Are you using the most recent version of Q1--2015?

**Comment by sIKE23** [comment]
Yes rolled a (pre)-alpha release this morning....

**Comment by ACG8** [comment]
Okay. I can't look at it right now, but I'll look at it this evening and get back to you.

**Comment by sIKE23** [comment]
that's fine just wanted to start capturing issues so we can start knocking
them down, we have until the end of the month
....

**Comment by ACG8** [comment]
This issue is not happening for me.

I open a game, play a beastmaster, and create a fireball in my inventory. I drag the BM and a fox into the arena. I play Fireball from my hand face-down. I check to make sure the BC is on. It is. I double click the face-down fireball. It flips face up (and does not prompt me for mana). I drag an arrow from the BM to the fox, triggering an attack. I select fireball. It prompts me to pay the mana which I do. My mana supply is reduced by 8 (but only by 8). The attack resolves.

I am not seeing this error at all. As long as the BC is on, attack spells only charge when cast.

However, I am seeing the message that fireball is spellbound, which is of course false. I'll see about fixing that.

**Comment by ACG8** [comment]
The castSpell function seems rather complicated to me. Do you mind if I look into simplifying/improving it?

**Comment by sIKE23** [comment]
Sure....

**Comment by sIKE23** [comment]
Placed a video recording in the dev folder for you to see what we are
seeing, I was able to reproduce Schwekgotts issue...

**Comment by sIKE23** [comment]
Hmm playing with this more...I think the BC got turned off some how and I didn't know it....

I think that maybe in Q2 that you should handle prepared Attack Spells differently than Bound Attack Spells. When the casting sequence for a prepared spell is complete you should discard it or prompt to discard it. For a bound spell this shouldn't happen.

Next item when Mage Targets a creature for a attack, I think it would be real cool if the Prepared Facedown Attack Card were included or if the Attack Spell is Bound to say a Wand but is not yet revealed, that it be included in the Attack options. Then if picked revealed and paid for.

**Comment by ACG8** [comment]
So this is working properly for you now? Though if the BC is turned off, you should not be able to cast the spell with the attack menu (the menu shouldn't even appear) in the first place, so there is still an issue to fix.

Yes, there are great plans for Q2. I think that is a great idea.

Regarding detecting face-down attack spells; that is certainly possible. I'll get right on it.

**Comment by ACG8** [comment]
Okay, I found the problem. The targeting arrow still brings up the menu even when the BC is off, and selecting a spell on the menu will still prompt you to pay the cost. This will be easy to fix, but it is in the actions file, so I would rather wait until you have finished your changes (I note that there are 2 action files right now) to fix this. Similarly, I'll wait on the face-down attack spell detection until there is only 1 action file again.

**Comment by sIKE23** [comment]
When my server OS died a couple of weeks ago, I had to reinstall, my IDE is
doing that and I have finally figured out (I hope) to turn it off. If you
see anything with a (#) you can ignore....

**Comment by sIKE23** [comment]
This is done and ready for you!

**Comment by sIKE23** [comment]
I should not be able to attach Force Hold to the Invisible Stalker.

**Comment by ACG8** [comment]
You mean because it can't be targeted? Right now, the invisible trait is left up to the players. Should it be enforced?

**Comment by sIKE23** [comment]
Not a targeting issue in that context, you can not attach it to a
creature with the Uncontainable trait....

**Comment by ACG8** [comment]
Yes, you are correct. I'll fix that.

**Comment by sIKE23** [comment]
I am unable to attach the Decoy Enchantment to anything.....

**Comment by sIKE23** [comment]
Detaching from Spawnpoints/Spellbind is still buggy, if you to take the facedown bound card from the Spawnpoint back into your hand the slot does not open back up and you can not bind another spell to it. Then if you move the Spawnpoint, the previously bound card reappears faceup and bound to the Spawnpoint.

**Comment by ACG8** [comment]
>Detaching from Spawnpoints/Spellbind is still buggy, if you to take the facedown bound card from the Spawnpoint back into your hand the slot does not open back up and you can not bind another spell to it. Then if you move the Spawnpoint, the previously bound card reappears faceup and bound to the Spawnpoint.

This should be fixed by https://github.com/sIKE23/Mage-Wars/commit/c27d56d57102440200617843e3d3d0c0d107a20f and https://github.com/sIKE23/Mage-Wars/commit/2fbc1fb852cbf12b6128f8a0a908dc99efadafca

**Comment by sIKE23** [comment]
That's what I thought, looks like those updates got lost somehow. I will
pull them back in again...

**Comment by ACG8** [comment]
They weren't lost; I only just fixed this issue.

**Comment by sIKE23** [comment]
I figured that out,....
