### ISSUE TITLE
Display Wall Cards horizontally using card sizes

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#170]

**Comment by anandaguneratne** [comment]
Are we sure we don't want to display them vertically? Horizontally, they look sort of awkward with all the other cards in a player's hand, and we could easily auto-realign them when played.

**Comment by sIKE23** [comment]
I am playing with it right now and so far I am not happy......

**Comment by sIKE23** [comment]
I was thinking it would be very nice to see the card as it should be viewed when you hovered over it......

**Comment by sIKE23** [comment]
Well, I finally got this all working, the cards do look a (just a tiny) bit weird in the players hand, but the pop up on the hover is very cool. I will pull it in and if you do not like, we can pull it back out.

**Comment by sIKE23** [comment]
You will have install the image pack in the dev folder to get the cards to present properly.

**Comment by anandaguneratne** [comment]
I can't find the right image pack - I installed the one in the Domination folder, but the walls are displaying incorrectly.

Also, the new size of the board is overlapping the dice roll area now. I don't think we should fix this just yet, though, because we are going to need to make some other changes anyway to accommodate the new (variable-sized) modular boards.

**Comment by anandaguneratne** [comment]
Never mind, it works now. The new walls look good (if slightly odd in a player's hand; no way to move them over a bit so that the spacing is uniform?)

**Comment by sIKE23** [comment]
Not really, hand spacing is done under Options | Advanced Options which has
to be enabled under the Basic Options tab by checking the Enable Advance
Options Check Box.

I know that we are over lapping at this point. The question is what do you
think of the board size as it affects the tiles too. We can get three
creatures vertically on a zone tile. Nothing else changes.

I had not even considered Game Marker placement regarding Domination board
layout. I am wondering if I should pull my work from MCA on this aspect of
the game. Optimally we would need the left most center tile coordinates.
Think you could build that into your algorithm? I could then call make a
board setup function to handle this.

</sIKE>

**Comment by anandaguneratne** [comment]
I think I like the new board/tile size. Plenty of space for all the cards in a zone.

The rest of this discussion will be tagged #166 

Are you suggesting that we work things like the dice-rolling area placement into the load map function? I kind of like that idea, actually. We could roll the other board types (such as the actual, non-modular standard board) into the function as well, start players off with a blank board, and require one of them to load a board before they can start playing. This has the advantage of letting us define tiles for modular and non-modular boards alike.

Are you saying that you want the leftmost center tile to always be in a particular location? I can definitely make that happen if you tell me what the location is. Keep in mind, though, that we already will need to make some of the player deployment locations (the location where cards from the hand are placed by default and where mass-detached cards are sent) variable; in particular, player deployment locations on the left side of the board will need to be made dependent on the width of the board so that they do not overlap the board. This will actually be pretty easy to do, since I plan to define zones during game setup, which will provide a basis for defining the locations of all the objects that are placed to the side of the board. 

But I guess my main point is, we don't need to keep the dice rolling area in a hard-coded location; we can have its location depend on the dimensions and location of the board used. So if we are figuring out where to place the board, simplicity might be the way to go, and I was thinking that the simplest thing to do is to place the upper left corner at (0,0).

However, I'm not sure how OCTGN manages the player view; it seems to me that the screen starts centered on (0,0), but placing a board might not shift the screen accordingly, which would look ugly. In which case the optimum position of the board would be with the center of the board at (0,0).

**Comment by sIKE23** [comment]
I am thinking yes we make the Dice Roll Area (DRA) work its own function
and things like modular board tiles can change the location of these items.

The initial display does center things on 0,0 so that is where we want to
work from. So, say you have map 21 v1 (its a great example from a planning
perspective) I start by always placing the first tile (center) at -250,
-250 and work out from there. That is what I have been doing but you can do
it differently.

0.000
..200
07.70
006..
000.0
#Map#

The 07.70 row would be the center row and we would want to place the DRA to
the left of the left most tile (-750, -250) by adding -135 to the x
coordinate of the tile being discussed.

</sIKE>

**Comment by anandaguneratne** [comment]
Okay, there is a MAJOR problem with displaying walls horizontally. When you double click to place a wall face-down, it is placed horizontally. This in of itself is not so bad (maybe we could rotate it or something), but the back of the card is also distorted, so that it is obvious when a player has played a wall spell. You will probably have to create an alternate back for walls.

I think my personal preference for walls is just to display them all vertically, turned sideways, by default. But let me know your thoughts on this issue.

**Comment by sIKE23** [comment]
Now that you point out the obvious. I will revert the walls back. We need
to be able to have the card backs set to default.

//FC

**Comment by sIKE23** [comment]
This is done though it will be pulled from the Q1 release waiting on Kelly to implement:

https://github.com/kellyelton/OCTGN/issues/1389

Will pull this over in to the Q2 release.

**Comment by sIKE23** [comment]
Done and closing
