### ISSUE TITLE
The Upkeep on Essence Drain is not automated

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#174]
Its trait is in the card.text part of the card data. I need to enhance the getTraitValue() to also check for the Upkeep value in this section of the card.

**Comment by anandaguneratne** [comment]
Actually, using #146 and the computeTraits function from the attacks.py document would take care of this.

**Comment by sIKE23** [comment]
The dictionary that it returns to me is not very useful. def
traitParser(traitStr): is much close to what I need but I need the +2 value
that is striped out.....

**Comment by sIKE23** [comment]
What will the data from "return traitDict" look like for Upkeep? I cant test against it so I have no clue on how to parse what is returned to me....

**Comment by anandaguneratne** [comment]
Call computeTraits on the card you are reading (not the Essence Drain, but the card to which it is attached). This will return a dictionary of traits containing the entry "Upkeep:2". You can retrieve the value of X (for your function that reads Upkeep +X) from the returned dictionary by querying: dictionary.get('Upkeep',0) (if you have a different default value for cases where cards have no Upkeep cost, you can put that instead of 0).

So the function might look something like:

for card in table:
    if card.controller == me:
        upkeep = computeTraits(card).get('Upkeep',0)
        upkeepResolutionFunctionGoesHere(card,upkeep)

**Comment by sIKE23** [comment]
Can you look at my re-factored code in the dev\Upkeep folder and let me know if I am on the right track and solve one dilemma for me.

Say I cast Force Hold and Essence Drain on my opponents Blue Gremlin. During Upkeep I have to pay the Upkeep for the Force Hold and my Opponent has to pay the Upkeep for the Essence Drain. I am trying to use your functions as much as possible. Any ideas?

I haven't handled the Upkeep +X issue yet but that shouldn't be hard. Will "X" return True on the if upkeep: ?

**Comment by ACG8** [comment]
I would go with resolving upkeep for cards in initiative order (of course, then there is that weird Mind Control ruling, which requires an exception...ugh...). Have the player with initiative resolve upkeep on all their own cards and then have the other player resolve upkeep on theirs using remoteCall (if player is not the last player on the list, remoteCall(resolveUpkeep) on the next player). Not sure exactly how it should work, but something like that seems like the best option.

You can get the upkeep of any card in play using computeTraits(card).get('Upkeep') (returns None if no upkeep cost); you should pay attention to the speed of the upkeep phase, though, since computeTraits is currently not as fast as I would like (the spellDictionary in Q2 should improve this situation considerably). If you want to use computeTraits, it should take Mordok's Obelisk and Harshforge Monolith into account correctly when deciding what upkeep a card has already (except that I don't think it will take face-down cards into account for Harshforge Monolith, but it looks like you are only using it for creatures, so that is fine). 

I just modified the traitParser so that a +X trait will be read as a 0. So X would return False on the upkeep, unless the creature is gaining upkeep from some other source (which would add to 0)

**Comment by sIKE23** [comment]
I am not sure that the +0 is the right way to go, for Upkeep, the +X trait
for one card is the attached creatures level (I should be able to use
getAttachTarget() and then pull the card.level of the creature) and for the
other is the number of crush tokens on Stranglevine. (a simple if and look
at the number of crush tokens on the card).

So compute traits deals with who pays the upkeep on Essence Drain vs. Force
Hold properly?

This is the one that is baffling me as all of the other cards with Upkeep
the owner of the card is responsible for paying the Upkeep, this one the
owner of the card it is attached too. I think if I am the controller of the
creature I can use getAttachments and then loop through the list of
attached cards and if one is Essence Drain and I am not the owner if it I
pay the Mana...

I see no need in Intuitive order for the upkeep phase. It is almost always
done at the same time by both players (IRL + OCTGN) and I really do not
want one player doing nothing while waiting on the other player(s) to go
about resolving their upkeep phase. In the rare case that Initiative order
is important (just like Burns with Regeneration, one is automated the other
isn't) players can manually handle it.

**Comment by ACG8** [comment]
*I am not sure that the +0 is the right way to go, for Upkeep, the +X trait
for one card is the attached creatures level (I should be able to use
getAttachTarget() and then pull the card.level of the creature) and for the
other is the number of crush tokens on Stranglevine. (a simple if and look
at the number of crush tokens on the card).*

+0 is just to avoid errors. If you want +X upkeep to be handled, you'll have to add an exception for now. I can work upkeep computation into the spell dictionary, but for now it is not handled by computeTraits.

*So compute traits deals with who pays the upkeep on Essence Drain vs. Force
Hold properly?*

computeTraits computes all the adjusted traits of a card. If the card has essence drain attached to it, computeTraits adds 2 to its upkeep. If the card itself has an upkeep cost, computeTraits adds that cost to its upkeep.

*This is the one that is baffling me as all of the other cards with Upkeep
the owner of the card is responsible for paying the Upkeep, this one the
owner of the card it is attached too. I think if I am the controller of the
creature I can use getAttachments and then loop through the list of
attached cards and if one is Essence Drain and I am not the owner if it I
pay the Mana...*

Just loop through the cards you control, and if one of them has a face-up Essence Drain attached, increase its upkeep by 2. It doesn't really matter who controls the Essence Drain. (It has the same effect if you attach it to your own creatures). Or just call computeTraits on each card you control which does the same thing, but a bit more as well).

*I see no need in Intuitive order for the upkeep phase. It is almost always
done at the same time by both players (IRL + OCTGN) and I really do not
want one player doing nothing while waiting on the other player(s) to go
about resolving their upkeep phase. In the rare case that Initiative order
is important (just like Burns with Regeneration, one is automated the other
isn't) players can manually handle it.*

Yes, that is probably the easiest, least disruptive way to do it.

**Comment by sIKE23** [comment]
The more I think about it the more I am sure that Compute Traits is not
going to do what I need it to do. What you are saying is that if I control
a creature(Unicorn) and you put Force Hold on it (Upkeep +3) that I should
run computeTraits on the Unicorn and I will get back the amount of Upkeep I
should pay which should be 0 but will return 3. You are the player that
should be paying the 3 not me....

//FC

**Comment by ACG8** [comment]
No, that is not how it works. If you run computeTraits() on the Unicorn, it will return 0. If you run computeTraits() on the Force Hold, it will return 3. If you attach an Essence Drain to the Unicorn and then run computeTraits() on the Unicorn, it will return 2.

If each player only runs computeTraits on their own cards to determine the upkeep, each player will get the correct amount.
