### ISSUE TITLE
Automating Mana usage off of a spawnpoint

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#177]
Schwenkgott asked:
![spawnpoint](https://cloud.githubusercontent.com/assets/5695175/6312369/a39f9d80-b93b-11e4-9d0e-99b559be8bf5.jpg)
Spawnpoints have been added to the Spellbind feature added in the last week correct. From there it should not be to big of a leap to automate this in the castSpell() function I believe. What are your thoughts.

**Comment by anandaguneratne** [comment]
You don't even need the prompt.

The way binding cards works right now is that cards appropriate to a particular spawnpoint (or familiar) are "bound" to the spawnpoint, not "attached" to it. The game recognizes them as bound spells, and treats them differently from attachments (for instance, they are displayed below the card, rather than above it, and are not considered when computing the traits of the card). The game even knows which cards are appropriate to bind to which spawnpoints/familiars So if we tell players to bind the card that they want their spawnpoint to cast (which is simply done by dragging the card over the spawnpoint), then when the card is cast, you just have to check whether it is bound to a particular spawnpoint or not.

Some functions that you may find useful:

getBindTarget(*Card*) -> returns the card object to which *Card* is bound (or NoneType if *Card* is not bound to anything)
getBound(*Card*) -> returns the card object bound to *Card* (or NoneType if *Card* does not have any spells bound to it)

Actually, I've been meaning to talk to you about this. A lot of the prompts in the game are now obsolete, due to the game's improved understanding of its own state. For instance, there is no longer any reason for the act of revealing an enchantment to ask the player whether the target is a mage (for magebind), as the enchantment is perfectly capable of figuring that out for itself (even in the event that players put mage enchantments off to the side, we can just check if its target is appropriate, i.e. zone, and default to mage as the target if not). In general, fewer prompts are better, since that leads to a smoother gameplay experience.

**Comment by anandaguneratne** [comment]
Though it doesn't affect this issue directly, I should also mention that spells may currently only be bound during the Planning Phase (mainly so that there is no confusion as to whether a player is binding or attaching an enchantment to Fellella or Sersiryx). Do you think this is the best way to handle this?

**Comment by sIKE23** [comment]
Just so you are completely aware, I am a newb at python, I have been
learning the language as I go. At this point I can basically follow what
most of your functions are doing with a rudimental understanding.
Thankfully you comment well most of the time and that helps. I have figured
out that some of what I was doing before is could probably be done better
with your code. Lets leave what we have for now, and we (meaning mainly
you) can look at what existing code can be updated and stream lined for Q2.

As for bound rules. Objects likes Wands change out with a Quick Action how
is that handled at this point?

So for the castSpell() function we should be able to add in:

since they player will be double clicking on a bound card to reveal it
getBindTarget(*Card*)

it should return the spawnpoint, we then check for how/if and mana markers
exist

take that number subtract it from the spells casting cost then figure out
how much mana is needed from the mages mana pool along with any discounts

then build the question to ask if the player wants to spend the X mana from
the Spawnpoint and X  from the mages pool.

Does that sound about right?

//FC

**Comment by anandaguneratne** [comment]
"""
As for bound rules. Objects likes Wands change out with a Quick Action how
is that handled at this point?
"""
Currently, it isn't. I can (and will) change those to allow players to change the bound spell during the action phase, which should help with that for now.

"""
So for the castSpell() function we should be able to add in:

since they player will be double clicking on a bound card to reveal it
getBindTarget(*Card*)

it should return the spawnpoint, we then check for how/if and mana markers
exist

take that number subtract it from the spells casting cost then figure out
how much mana is needed from the mages mana pool along with any discounts

then build the question to ask if the player wants to spend the X mana from
the Spawnpoint and X  from the mages pool.
"""

Yes, that sounds about right. If I am not mistaken, it is mandatory to use mana from a spawnpoint/familiar before using your mage's, but I guess it is still good to ask.

**Comment by sIKE23** [comment]
The question is do they want commit to spending X + Y mana to cast the
spell. X is Spawnpoint Mana and Y is Mages Mana. The math will use up all
of the Spawnpoint Mana's first then the rest will come out of the Mages
mana pool.

//FC

**Comment by anandaguneratne** [comment]
Sounds good. Maybe say "X mana from <spawnpoint.name> and Y mana from your personal supply" so it is explicit.

**Comment by sIKE23** [comment]
That is the intent. We do the math, enforcing the rules, and prompt with
the question  worded properly for there approval....

//FC

**Comment by sIKE23** [comment]
Will make this a issue for Q2...
