### ISSUE TITLE
Phases not working properly

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#191]
Phases are no longer working properly. Pressing Ctrl+Down does not always take the player to correct phase. Probably easiest just to open OCTGN with 2 players (or yourself, with 2 instances of OCTGN running) and go through the phases to see what I mean.

**Comment by sIKE23** [comment]
I have been re-working the Phase management for the last couple of days, time permitting. I have a good idea (mostly) of what I need to do to get it done. The problem is it all intertwined with player colors and initiative markers also, the whole thing is one big bolted on piece of spaghetti code with tendrils everywhere. I have been going down the rabbit hole for a bit now, but this ends up with we wanting to fix all of it. I want to be able to say: MASSIVE improvements to Phase and Initiative Management

:)

Might be a couple of more days though.....

**Comment by ACG8** [comment]
Okay, great. I am in no particular hurry to release alpha, so best to make sure that everything works properly.

**Comment by sIKE23** [comment]
The second player is not able to signal that they are done with the current Phase and the game will not advance to the next phase as a result.

**Comment by ACG8** [comment]
Solved. The problem was that global variables are stored as strings, so in the line

```
	gameIsOver = eval(getGlobalVariable("GameIsOver"))
	if gameIsOver:	#don't advance phase once the game is done
		return
```

gameIsOver will always evaluate to True, because it is a non-empty string (that happens to be "False"), as opposed to the boolean False.

I'll upload this with my next commit.

**Comment by sIKE23** [comment]
Yep that makes total sense, OCTGN does some weird things that I keep
forgetting about.

**Comment by sIKE23** [comment]
You un-did work I did for the release specifically, Mage Channeling (#122). I asked which way you wanted me to go with this feature, do add to the mages channeling? If so we have to track for deletion of Mana Flower/Crystal and Harmonize on the mage. You said lets don't mess with that and go the way we do it with non-mages.

I agree we can do it better next quarter with your proposed solution but this was a promise I made to several players for this release, matter in fact this is the first issue listed for this release....

**Comment by sIKE23** [comment]
If we don't want it invisible we change from Whisper to Notify....

**Comment by ACG8** [comment]
I'm sorry, you're right. I had completely forgotten about that. I do now think that adjusting channeling is the better way to go, though.

**Comment by sIKE23** [comment]
If I came across as cross, I had been on a road trip for two days with my
kids, and I was grouchy as a result. I apologize for not being a bit more
even keel. Thanks very much for fixing the issue.

I really wish some of the error messages were bit less cryptic, I know many
of the issues as of late have been from my coding more than anything else.

//FC

**Comment by ACG8** [comment]
No worries! We all have off days.

I know what you mean about the error messages. My debug method mostly involves putting debug messages everywhere, but it takes forever.

**Comment by sIKE23** [comment]
That is what I do too, but I had no clue of where to start for those marker
messages other than I changed something that is now causing this, but what
I am learning is that most if the marker messages are due to the player not
being the card controller.

I am getting better at reading and understanding your code, it is so far
beyond those who came before you.

</sIKE>

**Comment by sIKE23** [comment]
Got another Inconsistent state. Marker not found on card. Issue

Game Log is here: MageWars-Dev\Testing\Inconsistent state.txt

I think it is the Harmonize on the Battle Forge.

**Comment by ACG8** [comment]
The problem occurred when you attempted to harmonize the Battle Forge (or any other channeling object) belonging to another player. Fixed by changing the way Harmonize is recognized.

**Comment by sIKE23** [comment]
That was the Priests Battleforge who Harmonized it.

**Comment by ACG8** [comment]
Well, let me know if it happens again.
