### ISSUE TITLE
Guard Marker is handled as a Toggle Marker it should be handled as an Add/Remove Marker

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#210]

**Comment by ACG8** [comment]
Should it, though?

Guarding is a state which may be on or off. To the best of my knowledge, there is no way for a creature to have multiple guards, nor a way to use them. This would seem to more appropriately be handled as a toggle rather than an add/remove. For markers like Burn, where a card can have multiple copies (and having multiples is relevant), add/remove is needed because you need to be able to fine-tune the number of markers. But with guard, it is either ON or OFF, so using one button to change it is sufficient. And as a general rule, we probably want to minimize the number of commands.

**Comment by sIKE23** [comment]
There is no off side of the guard marker, when the creature starts its next
Action Phase remove the Guard marker. Toggles intent is for two-sided
markers that flip over and exhaust.

**Comment by ACG8** [comment]
Yes, but it functions as a toggle. It is more efficient to use one command to handle it as opposed to two. Toggle is for boolean-valued variables, whereas add/remove is for integer-valued variables.

It may not have an off side, but it is simpler from the player's perspective if it is a toggle.

**Comment by ACG8** [comment]
I realize that there is no off side, and that it is used like add/remove markers in real life, but I am just suggesting that in OCTGN it would work better as a toggle with no OFF side.

**Comment by sIKE23** [comment]
That would leave the both adding/removing the Marker as Ctrl+G. I wonder if
it would be better to "Toggle" all of the markers like this. It would cut
in half the number of Key Maps we have.....

**Comment by ACG8** [comment]
Some of them, certainly. But only the ones that can't have multiples (Zombie, Vet, Taunt, etc.). Markers like Burn, Daze, Growth, etc. still need 2 keys because they can have multiple copies. I am all in favor of reducing the number of key mappings.

**Comment by sIKE23** [comment]
Very true, I will have to look at what is there currently and work out what
can have multiple and what remains can be changed to be toggled...Q2
project for me, probably will just change this issue to morph it to this
idea.

**Comment by sIKE23** [comment]
Not going to take this any further....
