### ISSUE TITLE
Conceding in a 3+ Free for all ends the game

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#274]

**Comment by sIKE23** [comment]
@ACG8 
Been thinking on this one. Two ways to handle in my mind. 

First is to have a Player Global Variable that keeps track of each mages status and then we can check if number of mages that have conceded is one less than len(getPlayers()). 

Second is to have a generic Global Variable to track the number of mages that have conceded and test once again if that number is one less than len(getPlayers()).

Btw only track in more than two player games....

I have checked in thought 2 in the Master branch, it is just a rough draft though....

**Comment by ACG8** [comment]
I would go with the first option. Whenever you can have each object store
its own status, it is generally better to do so. We can define
player-specific global variables that can be accessed by other players,
then?

The second option works fine, though. Rather than counting, I would store a
list of the players; that way, you can't have errors where one player gets
counted twice (since you can enforce non-multiplicity).
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sIKE23** [comment]
Will test this code change tommorow
