### ISSUE TITLE
Planning Phase Timer

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#95]
This is a request from Schwenkgott. He would like a timer during the planning phase of the game. 

Here are my thoughts on the flow:

After initiative is determined pop a window asking if they would like to use a timer during the Planning Phase? If yes then ask how many minutes should the timer be set for. We then send these settings over to the remote player(s) if they agree then the timer will be used. 

If the timer is used, the phase is advanced to the Deployment phase automatically and we notify this into the chat window. 

Now for issues:

What if one player says yes and the other says no? Who should take precedence? The other thought is to use a configuration setting that is save and only if both players have the setting set to yes, then the timer will be used.

Long term it would be cool if we could come up with a "widget that would display the count down" I sure this is not currently possible in OCTGN.....but I have been known to be wrong...

**Comment by ACG8** [comment]
Okay, some rather exciting news. I figured out how to create a game timer without having to import any additional libraries. I just tested it out, and it works (I was able to have OCTGN keep track of time while doing other things like declaring attacks, playing spells, etc.).

Basically, I am passing function calls back and forth to avoid freezing any single player's computer. To do this, I make a function; the one I used for my example is:

```
def timerPing():
        mute()
        global testTime
        if str(time.ctime()) != testTime:
                testTime = str(time.ctime())
                notify("Time is " + str(time.ctime()))
        nextPlayer = players[-1]
        remoteCall(nextPlayer,"timerPing",[])
```

This function does the following:
1: It checks the current time. If the time is different than the current stored time, it gives a notification (you could, of course, set it so that it notifies you only when the time is at least a given increment past the current time).
2: It remoteCalls itself from the next player's computer.

The reason this works is that it sets up a loop, but does not use a single computer to do so. So while it is being called on the next computer, it frees up the last computer to handle other functions. (as opposed to a sleep function, which stops anything else happening on the current computer until it has completed. If OCTGN is handling something else when it receives the remotecall, it won't check the time until the current process is completed.

The downside is that this only works if you have more than 1 player (or at least, more than one instance of OCTGN running). I don't think this is a major concern, though, since solo players generally do not care about time restrictions.

My "inspiration" was the way the BC currently handles the attack sequence, passing functions between players. One (extremely minor) problem with the BC's method that I had before is that if you call another function while the other player is handling the attack sequence, it can interrupt the sequence (though this generally is not noticeable). I realized that this could be exploited to create a loop in the background of the game without tying up the game's resources.

Anyway, I think with a minimal amount of work, I could tailor this to create a timer for whatever purposes we want.

**Comment by ACG8** [comment]
Actually, now that I think about it, the applications go beyond just timing. This gives us a way to passively monitor anything we want without having to set specific triggers. For example, instead of checking for a player's death after each event that could possibly kill them, we could just check for a winner in the passive loop.

It is also important to note that this doesn't slow down the game, because the passive loop only runs when nothing else is running.

**Comment by ACG8** [comment]
Guess what? We have a timer now! And I was wrong; it is actually possible to bounce the update function off of yourself, so the timer works even in a 1 player (or dev-testing) game.

There are many ways that this can be improved, of course. I put it in its own file so that it will be easy to move to the other branches of the code (though maybe this was not necessary, in retrospect; it is pretty self-contained). We should probably just move it to actions.py, now that I think about it.

**Comment by ACG8** [comment]
I think this is basically done now, until we decide to add more features.
